4 module completed
js-tasks-ru/jsbasic-20210906-2_rychkovpavel pull request #4
Opened 2021-09-28 01:58 UTC by prychkov

2021-09-28 01:59 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-28 12:22 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-09-28 12:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-09-28 13:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-09-29 11:42 UTC, SinimaWath requested changes

2021-09-29 11:42 UTC, SinimaWath commented on 4-module/1-task/index.js
> +  }
Давай попробуем использовать навыки с массивами:
```
names.join('')
```

2021-09-29 11:42 UTC, SinimaWath commented on 4-module/3-task/index.js
> +      if (rows[i].cells[j].innerHTML < '18') {
Тут ты сравниваешь строки, а не числа. 

также если в innerHTML, будет `<div>18</div>`, то у тебя будет ошибка. Поэтому используй textContent

2021-09-29 11:42 UTC, SinimaWath commented on 5-module/2-task/index.js
> +    if (!(text.hasAttribute('hidden'))) {
Это стандартный атрибут, давай его использовать как свойство:
```
text.hidden
```

2021-09-30 17:28 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-30 17:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-09-30 18:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-10-01 05:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-10-01 23:02 UTC, SinimaWath requested changes

2021-10-01 23:02 UTC, SinimaWath commented on 5-module/3-task/index.js
> +  console.log(counterSlides);
Давай этот лог уберем, кажется он не нужен

2021-10-01 23:02 UTC, SinimaWath commented on 5-module/3-task/index.js
> +  slides[0].classList.toggle('activ');
Кажется класс **active**

2021-10-01 23:02 UTC, SinimaWath commented on 5-module/3-task/index.js
> +  slides[0].classList.toggle('activ');
Хотя не знаю зачем он нужен (

2021-10-02 04:31 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-10-02 04:36 UTC, prychkov commented on 5-module/3-task/index.js
> +  slides[0].classList.toggle('activ');
Это чтобы до обработчика события скрывать левую стрелку, чтобы при заходе на сайт впервые левая стрелка была сразу скрыта. Может есть другой вариант, подскажите направление я сделаю.

2021-10-02 07:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-10-02 20:10 UTC, SinimaWath approved these changes

2021-10-02 20:11 UTC, merged